name: profoundgodlibrary
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  flutter_bloc: ^7.0.0
  http: ^0.13.1
  shared_preferences: ^2.0.5
  flutter_easyrefresh: ^2.2.1
  flutter_spinkit: ^5.0.0
  rflutter_alert: ^2.0.2
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Fira Sans
      fonts:
        - asset: assets/fonts/Fira_Sans/FiraSans-Regular.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-Light.ttf
          weight: 100
        - asset: assets/fonts/Fira_Sans/FiraSans-SemiBold.ttf
          weight: 500

  uses-material-design: true
